title: Nandan Kumar | Software Engineer | Tech Speaker | Mentor | Featured on BBC, Saudi Gazette, Times Of India
description: Nandan Kumar | Software Engineer | Tech Speaker | Mentor | Featured on BBC, Saudi Gazette, Times Of India
show_downloads: true
show_navigation: true
remote_theme: sirius93/cayman-theme-custom
adSenseId : 3146543779775428
color:
  header: "#fff"
  gradient_color: "#FF9000"
  gradient_left: "#F7910F"
  gradient_right: "#FF9000"
  section_title: "#155799"
buttons:
  zip_url: https://nandan.dev
  zip_title: Home
  zip_hide: false
  tar_hide: true
  github_hide: true
google_analytics: G-4ZLTZWK8F2
google_analytics_anonymize: false
favicon: https://nandan.dev/images/favicon.ico
highlighter: rouge
use_math: true
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
url: "https://nandan.dev"
logo_url: https://nandan.dev/images/logo.webp
plugins:
  - jekyll-sitemap

