title: Nandan Kumar - Software Engineer | Techie who 'hacked' an Airline to retrieve his lost luggage | Public Speaker | Cyber Security Enthusiast | Photographer
description: Nandan Kumar - Software Engineer | Techie who 'hacked' an Airline to retrieve his lost luggage | Public Speaker | Cyber Security Enthusiast | Photographer
show_downloads: true
remote_theme: sirius93/cayman-theme-custom
color:
  header: "#fff"
  gradient_color: "#FF9000"
  gradient_left: "#F7910F"
  gradient_right: "#FF9000"
  section_title: "#155799"
buttons:
  zip_url: https://nandankumar.info
  zip_title: Home
  zip_hide: false
  tar_hide: true
  github_hide: true
google_analytics: G-4ZLTZWK8F2
google_analytics_anonymize: false
favicon: https://nandankumar.info/images/favicon.ico
highlighter: rouge
use_math: true
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
url: "https://nandankumar.info/pages"
plugins:
 - jekyll-sitemap

